Фикс игрушек. Фикс гиров СО и АВД
imperial-space/space-station14-public pull request #242
Opened 2024-06-11 16:03 UTC by KEEYNy

Фикс игрушек. Фикс гиров СО и АВД

2024-06-12 12:00 UTC, mirton14 commented on Resources/Prototypes/Imperial/seniorOfficer/seniorofficerclothing.yml
СО это старший офицер а не заместитель ГСБ или что то ещё. Он должен иметь тот же набор, что и обычные офицеры. Зачем ему расширенный пояс и газовая граната?

2024-06-12 12:04 UTC, mirton14 commented on Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
> +    eyes: ClothingEyesGlassesSecurity
Это как то относится к заявленным СО и АВД? И разве эти очки не должны лежать в шкафчиках СБ раундстартом?

2024-06-12 12:04 UTC, mirton14 commented on Resources/Prototypes/Roles/Jobs/Security/detective.yml
> +    eyes: ClothingEyesGlassesSecurity
Это как то относится к заявленным СО и АВД?

2024-06-12 12:05 UTC, mirton14 commented on Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
> +  - Detective
Нахрена ему доступ к детективу?

2024-06-13 10:33 UTC, KEEYNy commented on Resources/Prototypes/Imperial/IAA.yml
> -    eyes: ClothingEyesGlassesSunglasses
Случайно, уберу

2024-06-13 10:35 UTC, KEEYNy commented on Resources/Prototypes/Imperial/TFG/Toughguys/plushie_prototypes.yml
> +    - 0,0,1,1
В игрушки не влезает все что надо, да и контейнеры вмещают не меньше, чем сами весят. Из-за этого это вываливается из них

2024-06-13 10:37 UTC, KEEYNy commented on Resources/Prototypes/Imperial/seniorOfficer/seniorofficerclothing.yml
Газовая граната - стартовое снаряжение пояса СБ. РПС СО сделана такой же как у бригмеда, она и до этого была чуть больше обычной. СО имеет набор различного снаряжения для демонстрации

2024-06-13 10:51 UTC, KEEYNy commented on Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
> +  - Detective
Для того чтобы пояснять работу снаряжения детектива, консолей сканеров и прочего

2024-06-13 10:53 UTC, KEEYNy commented on Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
> +    eyes: ClothingEyesGlassesSecurity
Их нет

2024-06-15 10:37 UTC, KEEYNy commented on Resources/Prototypes/Roles/Jobs/Security/detective.yml
> +    eyes: ClothingEyesGlassesSecurity
Название пиара скороектировано

2024-06-22 11:15 UTC, ArturUr1 commented on Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
> +    eyes: ClothingEyesGlassesSecurity
Не должны они лежать раундстартом. Это Т1 технология РНД. Она не должна быть у каждого сотрудника раундстартом в СБ. Убрать у кадетов очки модернизированные.

2024-06-22 11:17 UTC, ArturUr1 requested changes

2024-06-22 11:17 UTC, ArturUr1 commented on Resources/Prototypes/Roles/Jobs/Security/detective.yml
> +    eyes: ClothingEyesGlassesSecurity
Верни стандартные очки. Не должно быть модернизированных очков у всех сотрудников СБ раундстартом. Тем более у детектива, который по СРП вообще задерживать не имеет право в одиночку. Зачем ему они?

2024-06-22 11:17 UTC, ArturUr1 commented on Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
> +    eyes: ClothingEyesGlassesSecurity
Аналогично. Убрать модернизированные очки у кадета. Хотят крутые очки - пусть ждут Т1 РНД и печатают. Уж не умрут за это время.

2024-06-23 15:47 UTC, KEEYNy commented on Resources/Prototypes/Roles/Jobs/Security/detective.yml
> +    eyes: ClothingEyesGlassesSecurity
Это позволяет проще вычислять преступников, сопоставлять айди с кпк

2024-06-28 22:55 UTC, ArturUr1 commented on Resources/Prototypes/Roles/Jobs/Security/detective.yml
> +    eyes: ClothingEyesGlassesSecurity
Это не должно быть по стандарту у всех сотрудников. Нужны некоторые ограничения для соблюдения баланса. Пусть кадеты и детектив стартуют без. Надо будет - напечатают

2024-08-01 15:18 UTC, KEEYNy reviewed
Очки убраны

2024-08-17 06:03 UTC, closed without merging