Реворк Христова
imperial-space/space-station14-public pull request #336
Opened 2024-07-13 16:13 UTC by Seven2280

## О чём PR
Полный реворк Христова.  А именно:
Двуручный, на магазинах, о магазинах: 
Два типа магазина: Обычные, бронебойные. Обычные 70 пирсинга, 20 структурного, 55 стамины. Бронебойные имеют 60 пирсинга, 60 структурного, 30 стамины. Каждый вмещает по 6 патрон.
Продаётся в чемодане с двумя обычными магазинами, цена в аплинке у агентов 16 ТК, нюкеров 20 ТК. Обычные патроны стоят 4 ТК, бронебойные 6 ТК.
## Почему / Баланс
Христов на данный момент полностью неиграбелен. Я спросил мнение большинства, буквально все считают что на данный момент он неиграбелен. 
![image](https://github.com/user-attachments/assets/726e92ae-6371-4f4a-8df7-9a52514ccb9e)
![image](https://github.com/user-attachments/assets/405c2919-11c9-4e22-acdf-95976f375ac4)
![image](https://github.com/user-attachments/assets/6eeae3a1-26a4-4b5f-a6b7-f5d65010ae6d)
Обусловлен такой высокий урон тем, что станция имеет от пирсинга очень много резистов от пуль. Но чтобы это не было прям сильно, пуль в Христове стало мало, этого не прям сильно хватит для убийства всей станции. Не волнуйтесь за эскадрон, агенты просто не смогут купить бронебойные боеприпасы для убийства эскадрона, им просто не хватит ТК. А в режим нюкеров вряд ли хоть когда нибудь дадут эскадрон.

## Технические детали
Оригинальный христов я не трогал, просто убрал его из аплинка.

## Медиа
![image](https://github.com/user-attachments/assets/6f7aaa9c-bed6-45e8-a2d2-7b4805ffa2fc)
![image](https://github.com/user-attachments/assets/f1233759-56da-4c04-9fff-14b36397ab60)
![image](https://github.com/user-attachments/assets/f02e6eeb-1434-48ac-ab27-72a2e4b13aab)

2024-07-13 19:14 UTC, ArnurMarat commented
Аплодисменты, реворк в котором нуждались. Христов станет играбельным, а возможно опера хоть в коем-то веке станут выигрывать

2024-07-13 19:15 UTC, ArnurMarat commented
Севен тигр

2024-07-13 19:18 UTC, Seven2280 commented
Спасибо братан

2024-07-13 23:21 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +  id: BulletSniper
Я так понимаю, что это обычные пули?

2024-07-13 23:21 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +  id: BulletSniperAP
Бронейбоки?

2024-07-13 23:21 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Бронебойность на что запланирована? На то, чтобы миновать стамина резисты? Не обычные?

2024-07-14 08:03 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +  id: BulletSniper
Да, правильно понимаешь.

2024-07-14 08:03 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +  id: BulletSniperAP
Да.

2024-07-14 08:03 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Бронебойность запланирована на то чтобы обычные миновать.

2024-07-14 10:41 UTC, ArturUr1 requested changes

2024-07-14 10:41 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
В таком случае:
а) Ты поставил это на стамина дамаг, а хотел на обычные. Тогда уж игнорирование надо было ставить на проджектайл
б) Убрать напрочь. Не надо плодить бронейбойки в билде, а тем более давать к ним такой легкий доступ. Учитывая 60 дамага С ИГНОРИРОВАНИЕМ брони - порождаешь имбу для синдиков и ЯО

2024-07-14 10:42 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Да и в чем реворк? Сделать имба патроны и поднять цену слегка?

2024-07-14 10:57 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Ну собственно на все это у меня есть ответ.
а) Я проверял работоспособность бронебоек на локалке, стрелял в уриста со скафом дедов бронебойками. Броню пробивали.
б) Не такая уж и имба если честно, всего 6 патрон. Стоимость 6 ТК, немало согласись? Тем более одиночные синдикаты просто не смогут купить к Христову бронебойные, им ТК не хватит. Можешь не волноваться за то что кто-то убьет дедов. А теперь насчет того почему без бронебоек это станет просто не очень оружие,   если взять СБуху с тактическим жилетом ей за 70 урона пирсинга нанесется меньше 30 урона. Ой, так у нас же еще есть наманченные капитаны с саблей, идеальными жилетами ОСЩ которых остается выносить только чайной, не думал что практически единственное нормальное оружие у нюкеров это точно не пули? Да даже Драгон Борн у меха лучше будет, делать христов без бронебоек убьет его полностью.

2024-07-14 11:02 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Я много где неправильно расставил запятые и точки. Но это не отменяет того факта что, отыгрывать от пуль - самоубийство (Разве что от зажиг не самоубийство)

2024-07-14 12:50 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Мало. В контексте ЯО мало. И оправдывать одну имбу другой имбой не надо. В игре не просто так не разбрасываются бронебойными и не вешают их на всё подряд (и тем более не делают их получение легким). Ты и так достаточно апнул урон для обычных патронов. Эти можешь сделать чем-то на подобии "пробивных", чтобы ломать стены. Понизить цену и добавить структурного урона. Но супер силой для уничтожения живой силы это быть не должно

2024-07-14 12:52 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
В общем от себя запрос на изменения убирать не буду. Судя даже по твоему голосованию - люди хотели от тебя полный реворк христова, а ты дал им первый вариант - добавление бронебойности и увеличение урона)

2024-07-14 13:49 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Помоему цена оправдана. И я не пытаюсь оправдать одну имбу другой имбой, я просто говорю факт. Отыгрывать от пуль сейчас - самоубийство, я лишь пытаюсь дать шанс пулям. Хочешь сказать что всё же слишком имба? Могу понизить урон до 45. Будет убивать за 3 выстрела, но задумайся. Сейчас не мета пуль, пули надо баффать, хоть как-то.

2024-07-14 13:49 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Не понимаю в чём тут не полный реворк христова. Я сделал его двуручным, поменял спрайты, сделал вместо того чтобы он был без магазинов, сделал с магазинами, чем не реворк?

2024-07-14 13:59 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Ты предвзят к бронебойках и тому что способно убить любого сквозь броню. Ты не хочешь поддерживать мету с паксом и другим таким, лишь из-за того что кто-то будет говорить типо такого: "О НЕТ!! МЕНЯ УБИЛИ БРОНЕБОЙКАМИ, КАКАЯ ЛЮТАЯ МЕТА, НАДО УБИРАТЬ СРОЧНО!! КОГДА ЭТО УБЕРУТ???" Но это проблема навыка, не проблема бронебоек. Я кучу раз убивал обычным огнестрельным оружием нюкеров, но также убивал копьями и другим таким и вот что я могу сказать. Некоторая мета бывает не очень сильной, просто людей убивают  не очень логичным оружием, вот они и считают что этого не должно существовать в игре. Помню даже когда ты пытался убить меня паксовым копьём, но увы, ничего не получилось.

2024-07-14 14:00 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Я много раз пытался убивать хоть сколько то смыслящих в игре людей паксовыми копьями, но обычно у меня это редко получалось.

2024-07-14 14:08 UTC, Seven2280 commented on Resources/Prototypes/Imperial/Hristov/snipers.yml
> +    ignoreResistances: true
Вообще к чему это я сказал. Может хоть стоит дать шанс Христову и посмотреть как он себя поведёт? Если окажется слишком имбой, я сразу же его понерфлю и всё будет как раньше.

2024-07-16 15:32 UTC, closed without merging