ШОКОМЫШЬ!!!
imperial-space/space-station14-public pull request #428
Opened 2024-11-06 17:23 UTC by ilyasassiks

## Представляю вашему вниманию - новый мидраунд антагонист - шокомышь

## About the PR

Мидраунд антагонист, который может появится при геймруле `ElectroMouseMigration` при условии 25 человек (может быть сбалансировано). В `Why/Balance` будут все расценки получения украденной энергии, и стоимость способностей
## Why / Balance

Игрокам очень понравилась шокомышь (123 лайка в дискорде на данный момент). Опросы: https://discord.com/channels/1040938900039929917/1278461010738413609/1303454438886998137 и https://discord.com/channels/1040938900039929917/1278461010738413609/1278479813216043019

Расценки:
Полный ЛКП - 30 энергии
Полная подстанция - 45
Полный СМЭС - 90

- Перегрузка света - 50
- Рывок - 25
- Эми - 75
- Хил - 100
- Щит - 125
- Скорость с проводами - 150
- Молния в одного - 200
- Вторая шокомышь - 300
- Улучшения - 500
- Возвышение - 1 500

Трата за использование:
- Перегрузка света - 25
- Рывок - бесплатно
- Эми - 20
- Хил - 30
- Щит - 20
- Скорость с проводами - 1/2 секунды
- Молния в одного - 10

Открытие: 
- Скорость с проводами: смэсы, подстанции
- Щит: ЛКП
- Перегрузка: Батареи из лазерных оружий
## Technical details

Не заметил багов при своем тесте, они возможны в будущем. По возможности буду стараться фиксить
## Media

[MEET THE ШОКОМЫШЬ!](https://youtu.be/9y6YK3pYQng)
- [+] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

`Content.Client.Imperial.ElectroMouseShield.Systems`, `Content.Client.Imperial.ElectroMouse`, `Content.Server.Imperial.ElectroMouse.EntitySystems`, `Content.Shared.ImperialElectroMouse.Events`, `Content.Shared.Imperial.ElectroMouse.Components`, `Content.Shared.Imperial.ElectroMouseShield.Components`, и также прототипы в `Resources\Prototypes\Imperial\Electromouse`, локализация в `Resources\Locale\ru-RU\Imperial\electromouse`, текстурки способностей `Resources\Textures\Imperial\electromouse.rsi`, магазин `Resources\Prototypes\Catalog\electromouse_catalog.yml`
**Changelog**

 Добавлена шокомышь - новый мидраунд антагонист. (Она была согласована чуть-чуть с Слизнефадом, скорее всего по ней будет вики) Страница на википедии - [будущийлинк](example.com)

2024-11-06 19:21 UTC, The-Fiafi commented
Был обнаружен баг при котором шокомышь станится, если нажмет на один из "источников пищи" вне радиуса ее досягаемости 

https://github.com/user-attachments/assets/4e010d22-c281-41e0-81d3-d180dc549c59

2024-11-06 19:33 UTC, The-Fiafi requested changes

2024-11-06 19:33 UTC, The-Fiafi commented on .vscode/settings.json
> +    "dotnet.preferCSharpExtension": true
Зачем? У нас проект не в стиле .NET Framework.

2024-11-06 19:33 UTC, The-Fiafi commented on Resources/Prototypes/Store/currency.yml
Все файлы прототипов должны находится по пути Imperial/Ваша_Разработка.

2024-11-06 19:33 UTC, The-Fiafi commented on Resources/Prototypes/Store/categories.yml
Все файлы прототипов должны находится по пути Imperial/Ваша_Разработка.

2024-11-06 19:33 UTC, The-Fiafi commented on Resources/Prototypes/Catalog/electromouse_catalog.yml
Все файлы прототипов должны находится по пути Imperial/Ваша_Разработка.

2024-11-06 19:33 UTC, The-Fiafi commented on Resources/Prototypes/Imperial/Electromouse/Actions/electromouse.yml
> +  - type: InstantAction
Акшены и должны быть маленькими? Лучше добавьте `itemIconStyle: BigAction`, чтобы они были размером с кнопку

2024-11-06 19:33 UTC, The-Fiafi commented on Resources/Prototypes/Imperial/Electromouse/electromouse.yml
> +  - type: CombatMode
Зачем шокомышке компонент комбат мода, если он не используется?

2024-11-06 19:33 UTC, The-Fiafi commented on Content.Server/Imperial/ElectroMouse/ElectroMouseSystem.cs
> +    public Vector2? Coordinates;
Перенесите переменные в компонент шокомыши. Сейчас если будет две и более шокомыши, то эта переменная будет общей для них обоих

2024-11-06 19:33 UTC, The-Fiafi commented on Content.Server/Imperial/ElectroMouse/ElectroMouseSystem.cs
> +    private const string ShopId = "ActionElectroMouseShop";
Эту тоже

2024-11-06 19:33 UTC, The-Fiafi commented on Resources/Prototypes/Catalog/electromouse_catalog.yml
> +  description: Все ваши становятся в 2 раза лучше
Опечатка.

2024-11-07 11:59 UTC, Qsan163 commented
дожрались

2024-11-07 15:32 UTC, mirton14 approved these changes

2024-11-07 15:36 UTC, merged

2024-11-07 15:38 UTC, ilyasassiks commented
дождались

2024-11-07 15:38 UTC, Seven2280 commented
Ого.

2024-11-07 18:03 UTC, krevetkqqq commented
а эээ. как

2024-11-07 18:06 UTC, Seven2280 commented
> а эээ. как

хз лол

2024-11-07 18:06 UTC, krevetkqqq commented
> > а эээ. как
> 
> хз лол

я понял как это я сделал. костыльный фикс сделаю позже

2024-11-07 18:10 UTC, Seven2280 commented
> > > а эээ. как
> > 
> > 
> > хз лол
> 
> я понял как это я сделал. костыльный фикс сделаю позже

А ещё у тебя изначально не проставлены галочки на возможность жрания СМЭС/ЛКП/подстанции. И если её проставить то на дебаг сборке сервер вылетит, на обычной такого не замечено.

2024-11-07 18:11 UTC, krevetkqqq commented
> > > > а эээ. как
> > > 
> > > 
> > > хз лол
> > 
> > 
> > я понял как это я сделал. костыльный фикс сделаю позже
> 
> А ещё у тебя изначально не проставлены галочки на возможность жрания СМЭС/ЛКП/подстанции. И если её проставить то на дебаг сборке сервер вылетит, на обычной такого не замечено.

хз. я на обычной играю. скорее всего к визденам проблема