Гамлет-Агент
imperial-space/space-station14-public pull request #43
Opened 2024-03-08 14:38 UTC by LightLava

## Немного о ПР'е
Добавлена возможность купить Синди-Гамлета вместе с крутой клеткой в аплинке.

## Почему?
Мне просто пришла идея о Гамлете-Синдиката после обновления визардов, где они добавили Синди-Кошку. 

## Технические детали
Клетка, её заполненная версия и листинг в аплинке объединены в одном прототипе. Гамлет-Агент имеет фракцию синдиката.

## Медиа

https://github.com/imperial-space/space-station14-public/assets/160842994/f46a6f26-ed86-4f96-b7a9-24c54e913f59

2024-03-09 03:39 UTC, Qsan163 commented on Resources/Prototypes/Imperial/Hamlet Ops/hamlet_ops.yml
> +    allowSpeech: true
Когнизин от Синдиката™©

2024-03-09 06:51 UTC, Bezllikii commented
Переименуй везде в своей работе Гамлета в хомяка.
Гамлет может быть только один, что бы не возникало путаницы у игроков при обсуждении вне раунда.

2024-03-09 12:38 UTC, LightLava commented on Resources/Prototypes/Imperial/Hamlet Ops/hamlet_ops.yml
> +    allowSpeech: true
Уэээ, это стандартный прототип гамлета. Галмет не может быть разумен, он тупой хомяк(((

2024-03-09 16:14 UTC, LightLava commented
> Переименуй везде в своей работе Гамлета в хомяка. Гамлет может быть только один, что бы не возникало путаницы у игроков при обсуждении вне раунда.

Это буквально идентичная копия Гамлета с взрывкой внутри. В том-то и прикол что он не должен выдавать себя сразу, и подвох узнаётся либо по громкому пиканию и описанию, либо в гостах.

2024-03-09 17:11 UTC, ArturUr1 requested changes

2024-03-09 17:11 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/HamletOps/syndicate_cage.yml
> +  name: хомячья клетка синдиката
Вот это нужно перенести в ftl файл, который ты создал.

2024-03-09 17:11 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/HamletOps/syndicate_cage.yml
> +  description: Обычная хомячья клетка с поилкой, но в стиле синдиката
Аналогично. Перенести в ftl.

2024-03-09 17:11 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/HamletOps/syndicate_cage.yml
> +  name: клетка с хомяком-агентом
Перенести в ftl. Вся локализация желательно должна находиться там.

2024-03-09 17:11 UTC, ArturUr1 commented on Resources/Prototypes/Imperial/HamletOps/syndicate_cage.yml
> +  description: Генетически точная копия всеми любимого ворчливого, милого и пушистого хомяка, с взрывчатой модификацией. Идеальный выбор для убийства одиночной цели.
Перенести в ftl. Вся локализация желательно должна находиться там.

2024-03-15 09:37 UTC, LightLava commented
Ура-ура, я сделал локализацию!

2024-03-16 11:52 UTC, ArturUr1 approved these changes
Молодец

2024-03-17 12:45 UTC, Koceryzkaa commented
Прикольно, а главное с иронией

2024-03-17 13:13 UTC, Koceryzkaa commented
Мердж when???

2024-03-18 17:19 UTC, LightLava commented
![IMG_20240318_143540](https://github.com/imperial-space/space-station14-public/assets/160842994/950068fe-c8da-44b1-ad89-0c9b281133f6)
Всех с соткой гамликов! :hamlet:

2024-03-18 17:21 UTC, LightLava commented
Так, я люто инактивил, сейчас примусь за гамлика.

2024-03-19 14:23 UTC, LightLava commented
### Когда мердж гамлика? 

> Завтра
> Если мерджа не было, читайте выше

2024-03-20 05:13 UTC, mirton14 approved these changes

2024-03-20 05:13 UTC, merged