Отображение должностей в рации
imperial-space/space-station14-public pull request #446
Opened 2024-11-14 00:13 UTC by Requiem4soul

### **В код Server.Radio были внесены изменения, позволяющие отображать должность.** 
В дискорд канале посвящённой данной разработке имеются видеодемонстрации работы данного кода 
(https://discord.com/channels/1040938900039929917/1304511097578979329).
![изображение](https://github.com/user-attachments/assets/3419a6c8-fa1c-4a42-b031-489b3f9b6ecf)

### **Как работает?**
**1)**
При помощи подключения:
`using Content.Server.Access.Systems;`
и
`[Dependency] private readonly IdCardSystem _idCardSystem = default!;`

Мы можем посмотреть какая **id карта** находится у игрока, который отправил сообщение в канал рации, а из карты уже **достать должность** данного игрока (Приоритет, который сделан офами: вначале проверяется карта в руке и только потом в pda).

**2)**
При помощи специального словара, **под ключ должности подбирается цвет данной должности**, который будет отображён в сообщении радиоканала. **В словаре должности все с строчными (маленькими) буквами, чтобы было проще добавлять должности, не создавая тысячи вариаций.** К примеру, без данного пришлось бы вбивать в словарь: "пцк", "пцК", "пЦк" и т.д.. Благодаря данной функции все вариации будут иметь значение "пцк".

**3)**
В name (`Name(messageSource)`) сохраняются данные  в **специальном порядке**, так как при неправильном порядке может или пропасть должность, или текстом отобразиться `[color=...`. Важно присвоить должность до `name = FormattedMessage.EscapeText(name);` . А после уже работать со стилем и цветом текста

**доп изменение**
Раньше использовалась проверка:
`
        if (name != Name(messageSource))
            _adminLogger.Add(LogType.Chat, LogImpact.Low, $"Radio message from {ToPrettyString(messageSource):user} as {name} on {channel.LocalizedName}: {message}");
        else
            _adminLogger.Add(LogType.Chat, LogImpact.Low, $"Radio message from {ToPrettyString(messageSource):user} on {channel.LocalizedName}: {message}");`

Так как name мы изменили, необходимо так же добавить в данное условие новый name, а так же явные использования моего кода. Это поможет определить где произошёл баг с радио не по вине моего кода, а где происходит баг по вине моего кода

### **Каковы отличия от других проектов?**
1) В моём варианте должности с именами будут выделяться более ярким/светлым (Void поправит, если что) что поможет лучше определять кто написал из отдела в канал отдела
2) Подчинённые ДСО (департаменту специальных операций) и Юр Депа (Юридический департамент) имеют уникальные цвета для должностей. Это поможет лучше понять иерархию новичкам, как и в целом напомнит о разделение ветвей власти в рамках игры
3) Мною лично был составлен словарь для разных вариаций названий. К примеру, в нём прописаны цвета для всех глав с должностями "ВРИО ГП", "ВРИО глава службы безопасности" и т.д. Словарь позволяет за О(1) найти необходимое значение для ключа

### **На ком не проверенно?**
1) Не удалось провести тестов на боргах, так как их нет в публичной локалке. **Но для них я всё равно создал особенный цвет должности, чтобы не пришлось мучиться с этим при подключении к приватному гиту**
2) Офицер "Синий Щит" - та же ситуация, что и с боргами. Особенный цвет для должности уже подключён

**Для всех остальных ролей мною производились тесты ручками при разных ситуациях. Ошибок мною не было выявлено**

### **Как агенту синдиката использовать данное нововведение?**
- Как поможет?
Если агент введёт в карте агента любую должность согласно манифесту (словарю), то данная должность и цвет должности будет отображено в канале рации, несмотря на то, что доступов данных игрок не имеет
- С чем не поможет?
Данный способ не работает на голомаски, так как из данных невозможно достать должность

2024-11-14 00:27 UTC, Requiem4soul commented
Очень прошу оставить особенные цвета для Юр Депа и Департамента Специальных Операций

2024-11-14 00:42 UTC, Requiem4soul commented
Ещё забыл добавить, что изначально делал на билде офов. Поэтому, для обновления так же есть рабочий код. Только куда его пихать - не знаю. Если скажете, могу прислать, ибо там переделывать придётся. Изменили методы, по котором определяется КПК и Должность в карте

2024-11-14 04:16 UTC, Oguz0k220 commented
А если человек введет своё название должности, которого в словарк нет ?

2024-11-14 10:48 UTC, Seven2280 commented
Круто, только "Офицер «Синий щит» "помоему так пишется поэтому скорее всего не будет отображаться его должность. Ну а возможно и по другому пишется.

2024-11-14 15:09 UTC, Requiem4soul commented
> Круто, только "Офицер «Синий щит» "помоему так пишется поэтому скорее всего не будет отображаться его должность. Ну а возможно и по другому пишется.

Привет! Спасибо огромное за похвалу!

По поводу ОСЩ, я так же добавил в словарь ключ "офицер /"синий щит/"", поэтому, работать должно будет.
` { "офицер \"синий щит\"", "#7d1010" },`
![изображение](https://github.com/user-attachments/assets/15369af9-5000-464c-ac02-8abcf543da13)

2024-11-14 18:00 UTC, Requiem4soul commented
> Круто, только "Офицер «Синий щит» "помоему так пишется поэтому скорее всего не будет отображаться его должность. Ну а возможно и по другому пишется.

А, я прошу прощения, вначале не заметил что вы использовали '«','»'. Пока так же добавил в словарь. 
Потом может сделаю, чтобы подобные знаки убирались, чтобы не вводить тысячу разных ключей в словарь. 
Спасибо за замечание

2024-11-14 19:46 UTC, Requiem4soul commented
### **Можно мерджить** 

**Теперь текст стал реально жирным**, цвета были скорректированы. Так же добавлены все возможные роли и наиболее частые их вариации и сокращения. 
![изображение](https://github.com/user-attachments/assets/8f499774-24b4-41fa-bf2f-1da2c507e424)

Так как текущее состояние около идеальное, сосредоточусь на фиксе багов, которые будут обнаружены

2024-11-14 20:42 UTC, ArnurMarat commented
Оу да, должность Яйца Сталина

2024-11-15 10:25 UTC, Requiem4soul commented
**Была добавлена существенная оптимизация.**
Теперь словарь статичен и не инициализируется каждый раз при вызове метода. Теперь код работает значительно быстрее.

**Так же это позволяет обращаться к словарю в других частях кода** (`using Content.Server.Radio.EntitySystems;`). 
На вход идёт значение string с именем должности (не важно заглавные или строчные буквы. Пример: "пЦк"), на выходе получается значение string цвета для данной роли (не само форматирование текста, всё ещё надо будет добавлять `$"[color={jobColor}] {text} [/color]"`. Для "пЦк" будет "yellow).

2024-11-15 17:04 UTC, Requiem4soul commented
### **Делаем всё для мерджа**
**Было перенесён функционал для данной задачи в папку Server.Imperial.Radio. В оригинальном коде осталось минимум необходимых изменений в коде.**
Были добавлены доп комментарии к новому коду
Так же указал как вернуть оригинальную работу кода, если после обновления будет что-то не так.

### **Функционал был ещё раз проверен в связи с крупным переносом. Проблем обнаружено не было**
![изображение](https://github.com/user-attachments/assets/1411e288-2540-4521-a4ad-d188f010763d)

2024-11-19 18:29 UTC, The-Fiafi requested changes
Добавьте комментарии в места, где вы изменяли код и измените захардкоженную таблицу профессий на прототипы

2024-11-19 18:29 UTC, The-Fiafi commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +        // Если из-за отображений должностей что-то сломается после какого-то обновления, то расскоментируйте данный код и закомментируйте код ниже, который я укажу. Данные действия просто вернут ста
Лишние комментарии об удалении или откатывании кода можно убрать. В них для нас нет никакого смысла

2024-11-19 18:29 UTC, The-Fiafi commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
Все изменения, которые вы вносите должны помечаться комментариями. Если изменения добавляют/удаляют/изменяют одну строку, то пишите: 
`<...> // Imperial НазваниеРазработки`. 
Если же изменения многострочные:
```cs
// Imperial НазваниеРазработки Start
<...>
// Imperial НазваниеРазработки End
```

2024-11-19 18:29 UTC, The-Fiafi commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
// Imperial НазваниеРазработки End

2024-11-19 18:29 UTC, The-Fiafi commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
// Imperial НазваниеРазработки Start

2024-11-19 18:29 UTC, The-Fiafi commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
>              _adminLogger.Add(LogType.Chat, LogImpact.Low, $"Radio message from {ToPrettyString(messageSource):user} as {name} on {channel.LocalizedName}: {message}");
// Imperial НазваниеРазработки End

2024-11-19 18:29 UTC, The-Fiafi commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +        if ((name != Name(messageSource)) && (name != newName))
Лушче закомментировать старый код , а после добавить измененный вами

2024-11-19 18:29 UTC, The-Fiafi commented on Content.Server/Imperial/Radio/JobPlayer.cs
> +    public static readonly Dictionary<string, string> JobColors = new()
Очень плохая идея. Либо создайте эту хеш-таблицу через CVar-ку, либо создайте прототип цвета имени для ID-карт. Что то по типу:
`- type: idCardColor
   color: "#FFF"
   jobName: Искусственный Интеллект
  displayName: ИИ
`
И просто итерируйтесь через IPrototypeManager по всем прототипам. Прототип желательнее, так как это даст большую гибкость

2024-11-19 21:15 UTC, Requiem4soul commented on Content.Server/Imperial/Radio/JobPlayer.cs
> +    public static readonly Dictionary<string, string> JobColors = new()
Словарь и есть хеш таблица, поэтому у неё то и О(1).

Идея хорошая, до первой карты агента или голомаски, где придётся для поиска нужного цвета проверь соответствие jobTitle с каждой картой до совпадения значений jobTitle и извлечением уже jobColor из нужной карты.

При моём подходе проверка всех ключей хотя бы была оптимизирована (О(1)) и сокращено количество проверок на соответствие значений (всё приведено к нижнему регистру. Бесполезно для хэш, но всё же). Поэтому затраты на поиск цвета что для обычной карты, что для карты был одинаково мал по ресурсам. 
Тут же я даже не понимаю как такое нужно будет оптимизировать. При таком подходе без словаря, нам придётся проходить по каждой карте (О(n)), при этом обращаться у каждой карты к компоненту jobTitle (что тоже будет занимать время **для каждой итерации**) чтобы сравнить равен ли он нашему jobTitle, чтобы потом взять её jobColor.

### Но, ладно
Сделаю компонент jobColor для всех карт, кроме агента. За карту агента и голомаску браться уже не буду, выше моего навыка динамического программирования

2024-11-20 08:47 UTC, CREAsTIVE commented
Считаю, что данное изменение немного не логично с точки зрения игровой вселенной. Максимум - использовать профессии из манифеста, объяснив это тем, что персонаж **запомнил** профессии определённых личностей, так же, как он и запомнил их имена. Тогда это будет чисто визуальный саппорт для игроков без дополнительной лишней нелогичной информации.

2024-11-20 17:08 UTC, KAZAK1984 commented
> Считаю, что данное изменение немного не логично с точки зрения игровой вселенной. Максимум - использовать профессии из манифеста, объяснив это тем, что персонаж **запомнил** профессии определённых личностей, так же, как он и запомнил их имена. Тогда это будет чисто визуальный саппорт для игроков без дополнительной лишней нелогичной информации.

Работки в рации существуют в первую очередь для упрощение бытия игрока, так смысл намеренно кастрировать фичу? Ради РП? Абсурд. Это явно не тот прикол, который должен иметь ЭХЭРПЭ объяснение

2024-11-20 17:19 UTC, Seven2280 commented
> > Считаю, что данное изменение немного не логично с точки зрения игровой вселенной. Максимум - использовать профессии из манифеста, объяснив это тем, что персонаж **запомнил** профессии определённых личностей, так же, как он и запомнил их имена. Тогда это будет чисто визуальный саппорт для игроков без дополнительной лишней нелогичной информации.
> 
> Работки в рации существуют в первую очередь для упрощение бытия игрока, так смысл намеренно кастрировать фичу? Ради РП? Абсурд. Это явно не тот прикол, который должен иметь ЭХЭРПЭ объяснение

Такой прикол у нюкеров имеет объяснение, имплант вокодера.

2024-11-20 19:58 UTC, Requiem4soul commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +        // Если из-за отображений должностей что-то сломается после какого-то обновления, то расскоментируйте данный код и закомментируйте код ниже, который я укажу. Данные действия просто вернут ста
Исправлено на:
`// Imperial "Отображение должностей в рации" Start
        // name = FormattedMessage.EscapeText(name);

        string? newName = _jobPlayer.CompletedJobAndPlayer(messageSource, name);
        name = newName;
        // Imperial "Отображение должностей в рации" End`

2024-11-20 20:32 UTC, CREAsTIVE commented
> Работки в рации существуют в первую очередь для упрощение бытия игрока, так смысл намеренно кастрировать фичу? Ради РП? Абсурд. Это явно не тот прикол, который должен иметь ЭХЭРПЭ объяснение

Ну... В целом да. Не могу придумать аргументов против. Всё равно можно будет какое то объяснение придумать, я думаю...

2024-11-20 20:39 UTC, The-Fiafi commented on Content.Server/Radio/EntitySystems/RadioSystem.cs
> +        // Если из-за отображений должностей что-то сломается после какого-то обновления, то расскоментируйте данный код и закомментируйте код ниже, который я укажу. Данные действия просто вернут ста
Названием вашей разработки является непосредственно ветка, которую вы хотите слить, но поскольку вы у себя это делали в stable-develop, то лучше назвать разработку в честь вашей главной системы. То есть: `// Imperial JobPlayerAndColor

2024-11-20 21:03 UTC, Requiem4soul commented
Я уже не могу понять что я тыкаю. Башка минус

2024-11-20 21:14 UTC, Requiem4soul commented
1) Было проверено что словарь заполняется единожды, а не каждый раз
![изображение](https://github.com/user-attachments/assets/0c7d5217-2962-4938-8df1-1c4b63e1b585)

2) Проведены тесты, чтобы удостоверится что после переработки кода всё работает
![изображение](https://github.com/user-attachments/assets/d9cf62aa-a130-45ca-9253-34113372b91f)

![изображение](https://github.com/user-attachments/assets/c087ae04-dc05-4f24-9604-0fb193d86393)

2024-12-29 11:30 UTC, Requiem4soul commented
Прошла эпоха, удачи вам парни. Надеюсь, вы однажды уберёте из выбора ВВО и будете бороться с метакомпашками

Закрываю, так как старая версия + коммент Миртона на апстримовской версии

2024-12-29 11:30 UTC, closed without merging