Гуманитарная помощь для геймеров
imperial-space/space-station14-public pull request #449
Opened 2024-11-20 15:23 UTC by Seven2280

# О чём PR
ОТВЕТСТВЕННЫЕ ЗА РЕСПРАЙТ: mcdonaldsobamaburger, sentryprimis. Раньше велась работа  над респрайтом отдела СБ.... Но она так и не завершилась, вскоре работа была восстановлена и доделана. 

# Медиа
![изображение](https://github.com/user-attachments/assets/b329245d-7150-42a3-b1f4-0e98b6f7af2c)
![изображение](https://github.com/user-attachments/assets/85e68fd3-ab10-4337-8adf-fd14d69e356e)
![изображение](https://github.com/user-attachments/assets/a04d5741-122f-4d72-94e8-809e76616865)

# Техническая часть 
Была заменена только мета и спрайты, ничего сложного.

2024-11-20 17:06 UTC, ArnurMarat commented
Продвигаем

2024-11-20 17:20 UTC, Seven2280 commented
Ента порно

2024-11-20 17:48 UTC, Mcdonaldsobamaburger commented
человек яйца

2024-11-20 17:57 UTC, ZaArturSharkRUS1 commented
Берем!

2024-11-20 23:11 UTC, hsffss14 commented
как тут комментарии писать?
![Uploading ae5a0f2c1faa2cfa2f4e83f767544177.png…]()

2024-11-20 23:11 UTC, hsffss14 commented
![ae5a0f2c1faa2cfa2f4e83f767544177](https://github.com/user-attachments/assets/0c83edf5-3dff-4c56-92fd-8b9b371719f2)

2024-11-22 11:14 UTC, Qsan163 commented
гейминг пришел

2024-11-22 21:35 UTC, Axxelium commented
Данная гуманитарка просто необходима геймерам ИС!!! Мы тут умираем

2024-11-29 22:21 UTC, NeronClaudius requested changes
Цвета норм, но слишком "квадратный" стиль, в общую стилистику не вписывается. Если и респрайтить, то под общий стиль или все сразу. Желательно поменять

2024-11-29 22:27 UTC, Mcdonaldsobamaburger commented
Сб респрайтнуто полностью, прям вообще все. Карго респрайтнуто, рнд респрайтнуто, инж тоже давно сделан, но не залит. Под стилистику вполне вписывается, много раз проверяли

2024-11-29 22:33 UTC, NeronClaudius commented
![image](https://github.com/user-attachments/assets/1b6f4035-5978-4220-906f-6a67d7f2123f)
и на перчатках. Однотонные квадраты. Такого у нас нет щас

2024-11-29 22:43 UTC, Mcdonaldsobamaburger commented
![image-51](https://github.com/user-attachments/assets/46e33c45-8170-4847-a17e-2c618a4d317f)
![image-261](https://github.com/user-attachments/assets/6a8523c0-4a4a-4a6a-a42b-591c3d12b503)
Кубики использовались и до этого. + Это добавляет обьема

2024-11-30 20:20 UTC, Bl1tz542 commented
Спрайт неплох, но на SyndTest лучше спрайты, хотя работы одних и тех же художников. Мне кажется, что над SyndTest они больше старались нежели на так называемый импэриал спэйс.

2024-11-30 20:22 UTC, Axxelium commented
> Спрайт неплох, но на SyndTest лучше спрайты, хотя работы одних и тех же художников. Мне кажется, что над SyndTest они больше старались нежели на так называемый импэриал спэйс.

Дело не в этом, они эти спрайты довно наколякали, тогда у них опыта меньше было чем ныне

2024-12-03 14:38 UTC, LightLava commented
ПРОКЛЯТИЕ СИНКА ФОРКА!

2024-12-25 20:40 UTC, Seven2280 commented
КУБИКИ ИСПРАВЛЕНЫ

2024-12-25 21:45 UTC, Requiem4soul commented
> КУБИКИ ИСПРАВЛЕНЫ

Хвалишься крутой прессухой? Фотки будут?

2024-12-26 05:30 UTC, Seven2280 commented
> > КУБИКИ ИСПРАВЛЕНЫ
> 
> Хвалишься крутой прессухой? Фотки будут?

Неееет, смотрите коммиты!!!

2024-12-27 14:45 UTC, Mcdonaldsobamaburger commented
> Интересный факт кстати: Эти спрайты не должны были быть загружены в игру ( любой билд) вообще. Это эксперимент "как можно улучшить спрайты СБ" на основе уже готовых работ, что лицензированы под nc-by-sa 3.0 (не для коммерческих проектов) и eula (у большинства из них запрещено брать спрайты/код) . Можете замержить, коль не боитесь dmca

Ого. :exploding_head:

2024-12-27 15:26 UTC, Seven2280 commented
> > КУБИКИ ИСПРАВЛЕНЫ
> 
> Убил спрайты лишь бы хуй пойми куда загрузить 👍

"Убил" так не я убил и ты прекрасно об этом знаешь

2024-12-28 16:49 UTC, Seven2280 commented
А, окей.

2024-12-28 16:49 UTC, closed without merging

2025-01-07 16:57 UTC, Axxelium commented
Ночь пройдёт и наступит утро ясное